name: CI/CD Pipeline

permissions:
  contents: write
  id-token: write
  pages: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: kurocado-studio/styleguide/.github/workflows/composite.lint.yml@main
    secrets: inherit

  test:
    needs: lint
    uses: kurocado-studio/styleguide/.github/workflows/composite.test.yml@main
    secrets: inherit

  document:
    needs: test
    uses: kurocado-studio/styleguide/.github/workflows/composite.document.yml@main
    secrets: inherit

  release:
    needs: document
    uses: kurocado-studio/styleguide/.github/workflows/composite.release.yml@main
    secrets: inherit

  deploy:
    needs: release
    uses: kurocado-studio/styleguide/.github/workflows/composite.deploy.yml@main
    secrets: inherit
