name: CI/CD Pull Request

on:
  pull_request:

jobs:
  lint:
    uses: kurocado-studio/styleguide/.github/workflows/composite.lint.yml@main
    secrets: inherit

  test:
    needs: lint
    uses: kurocado-studio/styleguide/.github/workflows/composite.test.yml@main
    secrets: inherit
