name: CI/CD Main Pipeline

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.lint.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: lint
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.test.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: test
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      branch_name: ${{ github.ref_name }}

  deploy:
    needs: test
    uses: kurocado-studio/dev-ops/.github/workflows/workflow.deploy.yml@main
    with:
      branch_name: ${{ github.ref_name }}
    secrets:
      fly_api_token: ${{ secrets.FLY_API_TOKEN }}
