name: Deployment Pipeline

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev

jobs:
  deploy:
    name: Deploy
    if: github.event.pull_request.merged == true
    uses: kurocado-studio/styleguide/.github/actions/deploy@main
    with:
      commit_sha: ${{ github.event.pull_request.merge_commit_sha }}
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
