name: Deployment Pipeline

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev

jobs:
  deploy:
    name: Deploy
    if: github.event.pull_request.merged == true
    uses: kurocado-studio/styleguide/.github/workflows/composite.deployment.yml@main
    secrets: inherit
    with:
      commit_sha: ${{ github.event.pull_request.merge_commit_sha }}
